// The pure half of scripts/gen-asset-manifest.ts: turning a dist/ tree into the
// source text of src/server/asset-manifest.ts. Separated from the entry point
// so it can be tested — the path handling here is the one place a Windows
// separator would silently corrupt 300-odd imports, and that is not something
// `tsc` or a CI runner catches by being pointed at a different OS.
import { readdirSync, statSync } from 'node:fs';
import { join, relative, sep as nativeSep } from 'node:path';

/**
 * POSIX separators, always. The result becomes BOTH an import specifier and a
 * URL pathname key, so on Windows `assets\index-abc.js` would be interpolated
 * into `'../../dist/assets\index-abc.js'` — a JS string literal whose `\i` is a
 * bare `i`. Silently corrupted imports, and keys no request ever matches.
 */
export function toPosixPath(path: string, separator: string = nativeSep): string {
  return path.split(separator).join('/');
}

/** Every file under `dir`, relative to `base`, POSIX-separated and sorted. */
export function walk(dir: string, base: string = dir): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full, base));
    } else {
      out.push(toPosixPath(relative(base, full)));
    }
  }
  return out;
}

/**
 * The generated module: one `import ... with { type: 'file' }` per asset, and a
 * map from URL pathname to whatever that import resolves to — the real path
 * under `bun src/server/app.ts`, an embedded /$bunfs/ path in the compiled
 * binary.
 */
export function renderManifest(files: string[]): string {
  const lines: string[] = [
    '// @ts-nocheck — AUTO-GENERATED by scripts/gen-asset-manifest.ts.',
    "// File-asset imports use Bun's `with { type: 'file' }` attribute that TypeScript",
    '// does not understand without per-extension module declarations; suppressing.',
    '',
  ];

  files.forEach((file, i) => {
    lines.push(`import a${i} from '../../dist/${file}' with { type: 'file' };`);
  });
  lines.push('');
  lines.push('export const ASSET_MANIFEST: Record<string, string> = {');
  files.forEach((file, i) => {
    lines.push(`  '/${file}': a${i},`);
  });
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
