// Scans dist/ (the vite build output) and emits src/server/asset-manifest.ts
// with one `import file with { type: 'file' }` per asset. At runtime each
// import resolves to:
//   - the actual filesystem path when running via `bun src/server/app.ts` (dev)
//   - an embedded /$bunfs/ path when running the `bun build --compile` binary
// so the server reads from the same map either way.
import { readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(import.meta.url), '../..');
const DIST_DIR = join(ROOT, 'dist');
const OUT_PATH = join(ROOT, 'src/server/asset-manifest.ts');

function walk(dir: string, base: string = dir): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full, base));
    } else {
      out.push(relative(base, full));
    }
  }
  return out;
}

let files: string[];
try {
  files = walk(DIST_DIR).sort();
} catch {
  console.warn(`[asset-manifest] ${DIST_DIR} not found — writing empty stub. Run \`vite build\` first.`);
  files = [];
}

const lines: string[] = [
  '// @ts-nocheck — AUTO-GENERATED by scripts/gen-asset-manifest.ts.',
  "// File-asset imports use Bun's `with { type: 'file' }` attribute that TypeScript",
  '// does not understand without per-extension module declarations; suppressing.',
  '',
];

files.forEach((file, i) => {
  lines.push(`import a${i} from '../../dist/${file}' with { type: 'file' };`);
});
lines.push('');
lines.push('export const ASSET_MANIFEST: Record<string, string> = {');
files.forEach((file, i) => {
  lines.push(`  '/${file}': a${i},`);
});
lines.push('};');
lines.push('');

await Bun.write(OUT_PATH, lines.join('\n'));
console.log(`[asset-manifest] wrote ${files.length} entries → ${OUT_PATH}`);
